Repository AtmosFears/AtmosFears-FE, pull requests merged in 2023-05, with the labels that each got.

#17 Precise data for sensor on map displayed in a form of a popup
  .eslintrc
  .gitignore
  package.json
  src/components/Map/CircleComponent.tsx
  src/components/Map/MapComponent.tsx
  src/components/Map/PopupComponent.tsx
  src/models/SensorData.ts
  vite.config.ts
  yarn.lock
Labels: feature

#18 Create nav bar with routing to appropriate screens
  .eslintrc
  .prettierrc
  index.html
  package.json
  src/App.scss
  src/App.tsx
  src/Root.tsx
  src/__tests__/App.test.tsx
  src/__tests__/__snapshots__/App.test.tsx.snap
  src/assets/icons/wind-rose.svg
  src/assets/react.svg
  src/assets/vite.svg
  src/components/custom/CustomIcon.tsx
  src/components/modules/ModCal/.gitkeep
  src/components/modules/SpatialAirVis/.gitkeep
  src/components/modules/TimeSeries/.gitkeep
  src/components/modules/WindRose/.gitkeep
  src/components/shared/Map/MapPointer.tsx
  src/components/shared/Map/PointerPopup.tsx
  src/components/shared/Map/index.tsx
  src/constants/index.ts
  src/constants/paths.ts
  src/core/NavBar.tsx
  src/index.scss
  src/index.tsx
  src/pages/ErrorPage.tsx
  src/pages/index.ts
  src/pages/modules/ModCalPage.tsx
  src/pages/modules/SpatialAirVisPage.tsx
  src/pages/modules/TimeSeriesPage.tsx
  src/pages/modules/WindRosePage.tsx
  src/scss/main.scss
  src/types/models/SensorData.ts
  tailwind.config.cjs
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: feature

#19 Improve nav-bar styles
  .eslintrc
  .prettierrc
  .vscode/settings.json
  package.json
  src/components/shared/Map/MapPointer.tsx
  src/core/NavBar.tsx
  src/core/NavBar/ActiveLinkIndicator.tsx
  src/core/NavBar/NavBarLink.tsx
  src/core/NavBar/NavBarLinkFlyout.tsx
  src/core/NavBar/index.tsx
  src/scss/_layout.scss
  src/scss/main.scss
  tailwind.config.cjs
  vite.config.ts
  yarn.lock
Labels: enhancement

#21 map color scale
  src/components/shared/Map/MapPointer.tsx
  src/components/shared/Map/index.tsx
  src/constants/colors.ts
  src/constants/index.ts
  src/constants/pollution.ts
  yarn.lock
Labels: enhancement, feature

#20 Feat/timeseries
  .eslintrc
  package.json
  src/components/TimeSeries/TimeSeries.tsx
  src/components/TimeSeries/TimeSeriesChart.tsx
  src/components/TimeSeries/TimeSeriesForm.tsx
  src/mocks/timeSeries/stations.json
  src/mocks/timeSeries/timeSeries.json
  src/pages/modules/TimeSeriesPage.tsx
  src/types/models/timeSeries.tsx
  yarn.lock
Labels: feature

#22 Feat/avg reports (TMP)
  package.json
  src/components/modules/SpatialAirVis/.gitkeep
  src/components/modules/SpatialAirVis/SpatialAirVis.tsx
  src/index.tsx
  src/mocks/avg-data.json
  src/pages/index.ts
  src/pages/modules/AverageTimeReportsPage.tsx
  src/types/models/AirQuality.ts
  yarn.lock
Labels: feature

#25 Fix nav bar being overlapped by map
  src/Root.tsx
  src/core/NavBar/index.tsx
  src/pages/modules/SpatialAirVisPage.tsx
Labels: fix
